name: Terraform Deployment

on:
  push:
    branches:
      - dev
      - staging
      - release  # release branch triggers prod workspace

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      TF_WORKSPACE: dev  # default

    steps:
      # 1️⃣ Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.6

      # 3️⃣ Determine workspace based on branch
      - name: Set Terraform Workspace
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}

          if [ "$BRANCH_NAME" == "dev" ]; then
            echo "TF_WORKSPACE=dev" >> $GITHUB_ENV
          elif [ "$BRANCH_NAME" == "staging" ]; then
            echo "TF_WORKSPACE=staging" >> $GITHUB_ENV
          elif [ "$BRANCH_NAME" == "release" ]; then
            echo "TF_WORKSPACE=prod" >> $GITHUB_ENV
          else
            echo "TF_WORKSPACE=dev" >> $GITHUB_ENV
          fi

      # 4️⃣ Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_${{ env.TF_WORKSPACE | upper }} }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_${{ env.TF_WORKSPACE | upper }} }}
          aws-region: ${{ secrets.AWS_REGION_${{ env.TF_WORKSPACE | upper }} }}

      # 5️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init

      # 6️⃣ Select or Create Workspace
      - name: Select Terraform Workspace
        run: |
          terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE

      # 7️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # 8️⃣ Terraform Apply (manual approval for prod)
      - name: Terraform Apply
        if: github.ref != 'refs/heads/release'  # automatic for dev/staging
        run: terraform apply -auto-approve

      - name: Terraform Apply Prod (manual approval)
        if: github.ref == 'refs/heads/release'
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: terraform apply
