name: Terraform Deployment

on:
  push:
    branches:
      - dev
      - staging
      - release  

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'release' && 'prod' && 'dev' || github.ref_name }}

    permissions:
      id-token: write    
      contents: read       

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.2
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::253490770638:role/GitHubTerraformRole
          aws-region: ap-south-1
      - name: Set Terraform Workspace
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          if [ "$BRANCH_NAME" == "dev" ]; then
            echo "WORKSPACE=dev" >> $GITHUB_ENV
          elif [ "$BRANCH_NAME" == "staging" ]; then
            echo "WORKSPACE=staging" >> $GITHUB_ENV
          elif [ "$BRANCH_NAME" == "release" ]; then
            echo "WORKSPACE=prod" >> $GITHUB_ENV
          fi

      - name: Terraform Init
        run: terraform init -input=false

      - name: Select Terraform Workspace
        run: terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
